config/routes.rb
require "admin_constraint"
require "sidekiq/web"

Rails.application.routes.draw do
  root "welcome#index"
  get "/search" => "welcome#search", as: "search"

  ########
  # Blog #
  ########

  get "/blog" => redirect( "http://" +
      (Rails.env.production? ? "blog.stripstarter.org" : "blog.dev") 
    ), :as => :blog
  get "/blog/about" => redirect( "http://" +
      (Rails.env.production? ? "blog.stripstarter.org/about" : "blog.dev/about") 
    ), :as => :about

  #############
  # Campaigns #
  #############

  resources :campaigns
  get "/campaigns/search" => "campaigns#search", as: "campaign_search"
  get "/campaigns/:id/finish" => "campaigns#finish", as: "campaign_finish"
  post "/campaigns/:id/submit" => "campaigns#submit", as: "campaign_submit"

  ############
  # Sessions #
  ############

  resources :user_sessions
  get "/login" => "user_sessions#new", as: "login"
  get "/logout" => "user_sessions#destroy", as: "logout"

  ##############
  # Performers #
  ##############

  get "/performers/search" => "performers#search", as: "performer_search"
  get "/performers/:performer_id" => "performers#show"

  #########
  # Users #
  #########

  resources :users, except: :index
  resources :pledgers, controller: "users", type: "Pledger"
  resources :performers, controller: "users", type: "Performer"

  ###########
  # Pledges #
  ###########

  post "/pledges" => "pledges#create"
  get "/users/:user_id/pledges" => "pledges#index"
  get "/checkout" => "checkout#index", as: "checkout"
  get  "/checkout/new_customer" => "checkout#new_customer", as: "new_customer"
  post "/checkout/create_customer" => "checkout#create_customer", as: "create_customer"
  post "/checkout/confirm_pledge" => "checkout#confirm_pledge", as: "confirm_pledge"
  delete "/pledges/:id" => "pledges#destroy"

  ##########
  # Photos #
  ##########

  post "/photos" => "photos#create", as: "photos"
  get "/photos/:photo_id" => "photos#show", as: "photo"
  delete "/photos/:photo_id" => "photos#destroy", as: "photo_destroy" # fix

  #########
  # Admin #
  #########

  get "/admin/campaigns" => "admin#campaigns", as: "admin_campaigns"
  post "/admin/:campaign_id/approve" => "admin#approve", as: "admin_approve"
  post "/admin/:campaign_id/deny" => "admin#deny", as: "admin_deny"
  post "/admin/:campaign_id/cancel" => "admin#cancel", as: "admin_cancel"

  ######################
  # Sidekiq Monitoring #
  ######################

  constraints(AdminConstraint) do
    mount Sidekiq::Web => "/sidekiq"
  end

end

app/views/admin/campaigns.html.erb
<h3>Pending campaigns</h3>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th class="col-md-1">ID</th>
        <th class="col-md-3">Name</th>
        <th class="col-md-6">Photos</th>
        <th class="col-md-1"><!-- Approve --></th>
        <th class="col-md-1"><!-- Deny --></th>
      </tr>
      <% @in_review.each do |campaign| %>
        <tr>
          <td><%= campaign.id %></td>
          <td><%= link_to campaign.name.truncate(20), campaign_path(campaign) %></td>
          <td>
            <div class="col-xs-12">
              <% campaign.photos.limit(6).each do |photo| %>
                <div class="col-xs-1">
                  <%= link_to photo_path(photo_id: photo.id) do %>
                    <%= image_tag photo_path(photo, style: "thumb") %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <td>
            <%= link_to admin_approve_path(campaign_id: campaign.id), method: "post" do %>
              <button class="btn btn-success">+</button>
            <% end %>
          </td>
          <td>
            <%= link_to admin_deny_path(campaign_id: campaign.id), method: "post" do %>
              <button class="btn btn-danger">X</button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<h3>Completed campaigns</h3>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th class="col-md-1">ID</th>
        <th class="col-md-3">Name</th>
        <th class="col-md-6">Photos</th>
        <th class="col-md-1"><!-- N/A --></th>
        <th class="col-md-1"><!-- Cancel --></th>
      </tr>
      <% @completed.each do |campaign| %>
        <tr>
          <td><%= campaign.id %></td>
          <td><%= link_to campaign.name.truncate(20), campaign_path(campaign) %></td>
          <td>
            <div class="col-xs-12">
              <% campaign.photos.limit(6).each do |photo| %>
                <div class="col-xs-1">
                  <%= link_to photo_path(photo_id: photo.id) do %>
                    <%= image_tag photo_path(photo, style: "thumb") %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <td>
          </td>
          <td>
            <%= link_to admin_cancel_path(campaign_id: campaign.id), method: "post" do %>
              <button class="btn btn-danger">X</button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>