config/routes.rb
require "admin_constraint"
require "sidekiq/web"

Rails.application.routes.draw do
  root "welcome#index"
  get "/search" => "welcome#search", as: "search"

  ########
  # Blog #
  ########

  get "/blog" => redirect( "http://" +
      (Rails.env.production? ? "blog.stripstarter.org" : "blog.dev") 
    ), :as => :blog
  get "/blog/about" => redirect( "http://" +
      (Rails.env.production? ? "blog.stripstarter.org/about" : "blog.dev/about") 
    ), :as => :about

  #############
  # Campaigns #
  #############

  resources :campaigns
  get "/campaigns/search" => "campaigns#search", as: "campaign_search"
  get "/campaigns/:id/finish" => "campaigns#finish", as: "campaign_finish"
  post "/campaigns/:id/submit" => "campaigns#submit", as: "campaign_submit"

  ############
  # Sessions #
  ############

  resources :user_sessions
  get "/login" => "user_sessions#new", as: "login"
  get "/logout" => "user_sessions#destroy", as: "logout"

  ##############
  # Performers #
  ##############

  get "/performers/search" => "performers#search", as: "performer_search"
  get "/performers/:performer_id" => "performers#show"

  #########
  # Users #
  #########

  resources :users, except: :index
  resources :pledgers, controller: "users", type: "Pledger"
  resources :performers, controller: "users", type: "Performer"

  ###########
  # Pledges #
  ###########

  post "/pledges" => "pledges#create"
  get "/users/:user_id/pledges" => "pledges#index"
  get "/checkout" => "checkout#index", as: "checkout"
  get  "/checkout/new_customer" => "checkout#new_customer", as: "new_customer"
  post "/checkout/create_customer" => "checkout#create_customer", as: "create_customer"
  post "/checkout/confirm_pledge" => "checkout#confirm_pledge", as: "confirm_pledge"
  delete "/pledges/:id" => "pledges#destroy"

  ##########
  # Photos #
  ##########

  post "/photos" => "photos#create", as: "photos"
  get "/photos/:photo_id" => "photos#show", as: "photo"
  delete "/photos/:photo_id" => "photos#destroy", as: "photo_destroy" # fix

  #########
  # Admin #
  #########

  get "/admin/campaigns" => "admin#campaigns", as: "admin_campaigns"
  post "/admin/:campaign_id/approve" => "admin#approve", as: "admin_approve"
  post "/admin/:campaign_id/deny" => "admin#deny", as: "admin_deny"
  post "/admin/:campaign_id/cancel" => "admin#cancel", as: "admin_cancel"

  ######################
  # Sidekiq Monitoring #
  ######################

  constraints(AdminConstraint) do
    mount Sidekiq::Web => "/sidekiq"
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic

  ##########
  # Avatar #
  ##########

  has_attached_file :avatar,
                    styles: {
                      thumb: '100x100>',
                      square: '200x200#',
                      medium: '300x300>'
                    }

  validates_attachment  :avatar,
                        :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
                        :size => { :in => 0..2.megabytes }

  ###############
  # Travis hack #
  ###############

  if Rails.env.test?
    attr_accessor :password, :password_confirmation
  end

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..40},
                       :on => :create
  validates :password, :confirmation => true,
                       :length => {:within => 6..40},
                       :allow_blank => true,
                       :on => :update

  def name
    [first_name, last_name].join(" ")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_if_pledger, only: :show

  def index
    _rand = rand(Performer.count - 5)
    @performers = Performer.offset(_rand).first(5)
    respond_to do |format|
      format.html { render "performers/index" }
      format.json { render json: @performers, root: false }
    end
  end

  def show
    @user = current_user
    respond_to do |format|
      format.json { render json: @user }
      format.html
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Registration successful."
      StripstarterMailer.delay.welcome_email(@user.id)
      redirect_to user_path(@user)
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:notice] = "Successfully updated profile."
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end

  private

  def user_params
    (params["user"] || params["pledger"] || params["performer"]).permit(
      :avatar,
      :email,
      :first_name,
      :last_name,
      :password,
      :password_confirmation,
      :type
    )
  end

  def redirect_if_pledger
    @user = User.find(params[:id])
    if !current_user && @user.is_a?(Pledger)
      redirect_to performers_path
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: {class: "form-horizontal col-sm-6", role: "form"} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-6">
      <input name="user[first_name]" type="text" id="first_name" class="form-control" placeholder="First name">
    </div>
    <div class="col-sm-6">
      <input name="user[last_name]" type="text" id="last_name" class="form-control" placeholder="Last name">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <input name="user[email]" type="text" id="email" class="form-control" placeholder="Email">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-6">
      <input name="user[password]" type="password" id="password" class="form-control" placeholder="Password must be 8-40 characters...">
    </div>
    <div class="col-sm-6">
      <input name="user[password_confirmation]" type="password" id="password_confirmation" class="form-control" placeholder="Please confirm your password...">
    </div>
  </div>
  <div class="form-group">
    <div class="radio col-sm-6">
      <label>
        <input name="user[type]" type="radio" name="userTypeRadios" id="userTypeRadio1" value="Pledger">
        I am a pledger
      </label>
    </div>
  </div>
  <div class="form-group">
    <div class="radio col-sm-6">
      <label>
        <input name="user[type]" type="radio" name="userTypeRadios" id="userTypeRadio2" value="Performer">
        I am a performer
      </label>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-6">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-6 actions">
      <input type="submit" value="Submit" class="btn btn-success">
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-2">
    <%= image_tag @user.avatar.url(:thumb), class: "img-circle" %>
  </div>
</div>

<br />
<br />

<%= render 'form' %>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div>
  <%= image_tag @user.avatar.url(:thumb), class: "img-circle" %>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="row">
      <h3>
        <div class="col-md-8">Basic Info</div>
        <div class="col-md-4">
          <% if @user.id == current_user.try(:id) %>
            <small><%= link_to "Edit", edit_user_path(@user), class: "text-right" %></small>
          <% end %>
        </div>
      </h3>
    </div>
    <br />
    <div class="row">
      <div class="col-md-12">
        <table class="table table-striped">
          <tr><td>Name:</td><td><%= @user.name %></td></tr>
          <tr><td>Email:</td><td><%= @user.email %></td></tr>
        </table>
      </div>
    </div>

    <% if @user.is_a? Pledger %>
      <div class="row">
        <div class="col-md-12">
          <h3>Pledges</h3>
          <table class="table table-striped">
            <tr>
              <th>Campaign</th>
              <th>Value</th>
              <th></th>
            </tr>
            <% @user.pledges.each do |pledge| %>
              <tr>
                <td><%= pledge.campaign.try(:name) %></td>
                <td><%= pledge.amount %></td>
                <td>
                  <%= link_to "/pledges/#{pledge.id}", method: :delete do %>
                    <button class="btn btn-danger">X</button>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    <% end %>

    <% if @user.is_a?(Performer) %>
      <% if !@user.campaigns.active.blank? %>
        <div class="row">
          <h3>
            <div class="col-md-8">Campaigns</div>
            <div class="col-md-4"></div>
          </h3>
        </div>
        <br />
        <div class="row">
        <div class="col-md-12">
          <table class="table table-striped">
            <% @user.campaigns.active.each do |campaign| %>
              <tr>
                <td class="col-md-8"><%= link_to campaign.name, campaign_path(campaign) %></td>
                <td class="col-md-2"><%= "$#{campaign.amount}" %></td>
                <td class="col-md-1">
                  <% if @user.id == current_user.try(:id) %>
                    <%= link_to campaign_path(campaign), method: "delete" do %>
                      <button class="btn btn-danger">X</button>
                    <% end %>
                  <% end %>
                </td>
                <td class="col-md-1">
                  <% if @user.id == current_user.try(:id) %>
                    <%= link_to campaign_finish_path(id: campaign.id) do %>
                      <button class="btn btn-success">></button>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      <% end %>
      <% if !@user.campaigns.in_review.blank? && ( @user == current_user || current_admin? ) %>
        <div class="row">
          <h3>
            <div class="col-md-8">Campaigns (in review)</div>
            <div class="col-md-4"></div>
          </h3>
        </div>
        <br />
        <div class="row">
        <div class="col-md-12">
          <table class="table table-striped">
            <% @user.campaigns.in_review.each do |campaign| %>
              <tr>
                <td class="col-md-8"><%= campaign.name %></td>
                <td class="col-md-2"><%= campaign.amount %></td>
                <td class="col-md-1">
                  <%= link_to campaign_path(campaign), method: "delete" do %>
                    <button class="btn btn-danger">X</button>
                  <% end %>
                </td>
                <td class="col-md-1"></td>
              </tr>
            <% end %>
          </table>
        </div>
      <% end %>
    <% end %>
  </div>
</div>