config/routes.rb
require "admin_constraint"
require "sidekiq/web"

Rails.application.routes.draw do
  root "welcome#index"
  get "/search" => "welcome#search", as: "search"

  ########
  # Blog #
  ########

  get "/blog" => redirect( "http://" +
      (Rails.env.production? ? "blog.stripstarter.org" : "blog.dev") 
    ), :as => :blog
  get "/blog/about" => redirect( "http://" +
      (Rails.env.production? ? "blog.stripstarter.org/about" : "blog.dev/about") 
    ), :as => :about

  #############
  # Campaigns #
  #############

  resources :campaigns
  get "/campaigns/search" => "campaigns#search", as: "campaign_search"
  get "/campaigns/:id/finish" => "campaigns#finish", as: "campaign_finish"
  post "/campaigns/:id/submit" => "campaigns#submit", as: "campaign_submit"

  ############
  # Sessions #
  ############

  resources :user_sessions
  get "/login" => "user_sessions#new", as: "login"
  get "/logout" => "user_sessions#destroy", as: "logout"

  ##############
  # Performers #
  ##############

  get "/performers/search" => "performers#search", as: "performer_search"
  get "/performers/:performer_id" => "performers#show"

  #########
  # Users #
  #########

  resources :users, except: :index
  resources :pledgers, controller: "users", type: "Pledger"
  resources :performers, controller: "users", type: "Performer"

  ###########
  # Pledges #
  ###########

  post "/pledges" => "pledges#create"
  get "/users/:user_id/pledges" => "pledges#index"
  get "/checkout" => "checkout#index", as: "checkout"
  get  "/checkout/new_customer" => "checkout#new_customer", as: "new_customer"
  post "/checkout/create_customer" => "checkout#create_customer", as: "create_customer"
  post "/checkout/confirm_pledge" => "checkout#confirm_pledge", as: "confirm_pledge"
  delete "/pledges/:id" => "pledges#destroy"

  ##########
  # Photos #
  ##########

  post "/photos" => "photos#create", as: "photos"
  get "/photos/:photo_id" => "photos#show", as: "photo"
  delete "/photos/:photo_id" => "photos#destroy", as: "photo_destroy" # fix

  #########
  # Admin #
  #########

  get "/admin/campaigns" => "admin#campaigns", as: "admin_campaigns"
  post "/admin/:campaign_id/approve" => "admin#approve", as: "admin_approve"
  post "/admin/:campaign_id/deny" => "admin#deny", as: "admin_deny"
  post "/admin/:campaign_id/cancel" => "admin#cancel", as: "admin_cancel"

  ######################
  # Sidekiq Monitoring #
  ######################

  constraints(AdminConstraint) do
    mount Sidekiq::Web => "/sidekiq"
  end

end

app/views/shared/_footer.html.erb
    <footer class="site-footer">

  <div class="wrapper">

    <h2 class="footer-heading">Stripstarter</h2>

    <div class="footer-col-wrapper">
      <div class="footer-col  footer-col-1">
        <ul class="contact-list">
          <li>Stripstarter</li>
          <li><a href="mailto:stripstarter@gmail.com">stripstarter@gmail.com</a></li>
        </ul>
      </div>

      <div class="footer-col  footer-col-2">
        <ul class="social-media-list">
          
          <li>
            <a href="https://github.com/stripstarter">
              <span class="icon  icon--github">
                <svg viewBox="0 0 16 16">
                  <path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/>
                </svg>
              </span>

              <span class="username">stripstarter</span>
            </a>
          </li>
          

          
          <li>
            <a href="https://twitter.com/stripstarter">
              <span class="icon  icon--twitter">
                <svg viewBox="0 0 16 16">
                  <path fill="#828282" d="M15.969,3.058c-0.586,0.26-1.217,0.436-1.878,0.515c0.675-0.405,1.194-1.045,1.438-1.809
                  c-0.632,0.375-1.332,0.647-2.076,0.793c-0.596-0.636-1.446-1.033-2.387-1.033c-1.806,0-3.27,1.464-3.27,3.27 c0,0.256,0.029,0.506,0.085,0.745C5.163,5.404,2.753,4.102,1.14,2.124C0.859,2.607,0.698,3.168,0.698,3.767 c0,1.134,0.577,2.135,1.455,2.722C1.616,6.472,1.112,6.325,0.671,6.08c0,0.014,0,0.027,0,0.041c0,1.584,1.127,2.906,2.623,3.206 C3.02,9.402,2.731,9.442,2.433,9.442c-0.211,0-0.416-0.021-0.615-0.059c0.416,1.299,1.624,2.245,3.055,2.271 c-1.119,0.877-2.529,1.4-4.061,1.4c-0.264,0-0.524-0.015-0.78-0.046c1.447,0.928,3.166,1.469,5.013,1.469 c6.015,0,9.304-4.983,9.304-9.304c0-0.142-0.003-0.283-0.009-0.423C14.976,4.29,15.531,3.714,15.969,3.058z"/>
                </svg>
              </span>

              <span class="username">stripstarter</span>
            </a>
          </li>
          
        </ul>
      </div>

      <div class="footer-col  footer-col-3">
        <p class="text">Social crowdsourcing.</p>
      </div>
    </div>

  </div>

</footer>

app/views/shared/_logo_test.html.erb
<svg viewBox="0 0 600 300">

  <!-- Pattern -->
  <pattern 
           id="p-fire" 
           viewBox="30 100 186 200"
           patternUnits="userSpaceOnUse"
           width="216" height="200"
           x="-70" y="35">

    <!-- Fire -->
    <image xlink:href="http://i.minus.com/i0lOiSHAlws3M.gif" width="256" height="300"/>
  </pattern>

  <!-- Text -->
  <text text-anchor="middle"
        x="50%"
        y="50%"
        class="logo-test"
        >
    WELCOME TO
  </text>

  <text text-anchor="middle"
        x="50%"
        y="50%"
        dy=".75em"
        class="logo-test"
        >
    STRIPSTARTER
  </text>

</svg>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-logo" do %>
        <%= image_tag "logo_v1.png" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Campaigns", campaigns_path %></li>
        <li><%= link_to "Performers", performers_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Blog", blog_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-form navbar-left" role="search">
          <%= text_field_tag 'search_box', nil, placeholder: "Search" %>
        </li>
        <% if current_user %>
          <% if current_user.is_a? Pledger %>
            <% unless current_user.stripe_customer_id || current_admin? %>
              <li><%= link_to "Add Your Card", new_customer_path %></li>
            <% end %>
            <li><%= link_to "My Cart" + pending_pledges, checkout_path %></li>
          <% end %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Logout", logout_path %></li>
          <% if current_admin? %>
            <li>
              <a class="dropdown dropdown-toggle" data-toggle="dropdown">
                Admin
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Pending", admin_campaigns_path %></li>
              </ul>
            </li>
          <% end %>
        <% else %>
          <li><%= link_to "Register", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Logic for search box -->

<script type="text/javascript">
  
  function imgForAutocompleteItem(item){
    if (item.avatar_url === "") {
      return "";
    }
    else {
      return "<img class=\"search-result\" src=" + item.avatar_url + " />";
    }
  }

  $(function() {
    
    var currentCategory = "";

    $('#search_box').autocomplete({
      minLength: 2,
      source: '<%= search_path(:json) %>',

      focus: function(event, ui) {
        $('#search_box').val(ui.item.value);
        return false;
      },

      select: function(event, ui) {
        $('#search_box').val(ui.item.value);
        $('#link_origin_id').val(ui.item.id);
        return false;
      }}).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
        if (item.klass != currentCategory){
          ul.append("<li><strong>" + item.klass + "s</strong></li>");
        }
        currentCategory = item.klass;
        return $("<li></li>")
          .data( "autocomplete-item", item )
          .append("<div>" +
            imgForAutocompleteItem(item) +
            "<a href=" + item.url + ">" + item.value +  "</a>" +
            "</div>")
          .appendTo( ul );
    };
  });
</script>