config/routes.rb
require "admin_constraint"
require "sidekiq/web"

Rails.application.routes.draw do
  root "welcome#index"
  get "/search" => "welcome#search", as: "search"

  ########
  # Blog #
  ########

  get "/blog" => redirect( "http://" +
      (Rails.env.production? ? "blog.stripstarter.org" : "blog.dev") 
    ), :as => :blog
  get "/blog/about" => redirect( "http://" +
      (Rails.env.production? ? "blog.stripstarter.org/about" : "blog.dev/about") 
    ), :as => :about

  #############
  # Campaigns #
  #############

  resources :campaigns
  get "/campaigns/search" => "campaigns#search", as: "campaign_search"
  get "/campaigns/:id/finish" => "campaigns#finish", as: "campaign_finish"
  post "/campaigns/:id/submit" => "campaigns#submit", as: "campaign_submit"

  ############
  # Sessions #
  ############

  resources :user_sessions
  get "/login" => "user_sessions#new", as: "login"
  get "/logout" => "user_sessions#destroy", as: "logout"

  ##############
  # Performers #
  ##############

  get "/performers/search" => "performers#search", as: "performer_search"
  get "/performers/:performer_id" => "performers#show"

  #########
  # Users #
  #########

  resources :users, except: :index
  resources :pledgers, controller: "users", type: "Pledger"
  resources :performers, controller: "users", type: "Performer"

  ###########
  # Pledges #
  ###########

  post "/pledges" => "pledges#create"
  get "/users/:user_id/pledges" => "pledges#index"
  get "/checkout" => "checkout#index", as: "checkout"
  get  "/checkout/new_customer" => "checkout#new_customer", as: "new_customer"
  post "/checkout/create_customer" => "checkout#create_customer", as: "create_customer"
  post "/checkout/confirm_pledge" => "checkout#confirm_pledge", as: "confirm_pledge"
  delete "/pledges/:id" => "pledges#destroy"

  ##########
  # Photos #
  ##########

  post "/photos" => "photos#create", as: "photos"
  get "/photos/:photo_id" => "photos#show", as: "photo"
  delete "/photos/:photo_id" => "photos#destroy", as: "photo_destroy" # fix

  #########
  # Admin #
  #########

  get "/admin/campaigns" => "admin#campaigns", as: "admin_campaigns"
  post "/admin/:campaign_id/approve" => "admin#approve", as: "admin_approve"
  post "/admin/:campaign_id/deny" => "admin#deny", as: "admin_deny"
  post "/admin/:campaign_id/cancel" => "admin#cancel", as: "admin_cancel"

  ######################
  # Sidekiq Monitoring #
  ######################

  constraints(AdminConstraint) do
    mount Sidekiq::Web => "/sidekiq"
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  ################
  # Associations #
  ################

  has_many :campaign_feature_joins
  has_many :features, through: :campaign_feature_joins

  has_many :performances
  has_many :performers, through: :performances

  has_many :pledges
  has_many :pledgers, through: :pledges

  belongs_to :owner, class: User

  has_many :photos, through: :performances

  def users
    pledgers + performers
  end 

  validates_presence_of :owner

  ##########
  # Scopes #
  ##########

  def self.top(num = 5)
    includes(:pledges).all.sort_by(&:amount).last(num).reverse
  end

  scope :newest, ->() { order("campaigns.created_at DESC") }
  scope :active, ->() { where(status: "active") }
  scope :completed, ->() { where(status: "completed") }
  scope :canceled, ->() { where(status: "canceled") }
  scope :in_review, ->() { where(status: "in_review") }

  ##########
  # States #
  ##########

  state_machine :status, initial: :active do

    state :active, value: "active"
    state :in_review, value: "in_review"
    state :completed, value: "completed"
    state :canceled, value: "canceled"

    event :activate do
      transition inactive: :active
    end
    event :submit_for_review do
      transition active: :in_review
    end
    event :approve do
      transition in_review: :completed
    end
    event :deny do
      transition in_review: :active
    end
    event :cancel do
      transition [:active, :in_review, :completed] => :canceled
    end
    event :renew do
      transition canceled: :active
    end
  end

  #############
  # Searching #
  #############

  after_save :load_into_soulmate, unless: ->(){ Rails.env.test? }
  before_destroy :remove_from_soulmate

  def remove_from_soulmate
    Soulmate::Loader.new("campaign").remove "id" => id
  end

  def load_into_soulmate
    loader = Soulmate::Loader.new("campaign")
    loader.add({
      "id" => id,
      "term" => name,
      "klass" => self.class.name,
      "url" => Rails.application.routes.url_helpers.campaign_path(self)})
  end

  def self.search(term)
    matches = Soulmate::Matcher.new("campaign").matches_for_term(term)
    matches.collect do |match|
      {
        "id" => match["id"],
        "value" => match["term"],
        "klass" => match["klass"],
        "avatar_url" => "",
        "url" => match["url"]
      }
    end
  end

  def amount
    pledges.collect do |pledge|
      pledge.amount.to_i
    end.inject(:+).to_i
  end
  
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_filter :ensure_owner, only: [:edit, :update]
  before_filter :ensure_performer, only: [:finish, :submit]
  before_filter :ensure_owner_or_performer, only: :destroy

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.active
    @top_campaigns = Campaign.active.top(5)
    @newest_campaigns = Campaign.active.newest.first(5)
    respond_to do |format|
      format.json { render :json => @campaigns }
      format.html
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign = Campaign.find(params[:id])
    respond_to do |format|
      if @campaign.try(:active?) || current_admin?
        format.json { render json: @campaign }
        format.html
      else
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
        format.html do
          flash[:notice] = Stripstarter::Response::CAMPAIGN_NOT_FOUND
          redirect_to campaigns_path
        end
      end
    end
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
    @campaign ||= Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.owner = current_user

    respond_to do |format|
      if @campaign.save
        format.html do
          flash[:notice] = Stripstarter::Response::CAMPAIGN_CREATE_SUCCESS
          redirect_to @campaign
        end
        format.json { render nothing: true, status: 200 }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    @campaign ||= Campaign.find(params[:id])
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html do
          flash[:notice] = Stripstarter::Response::CAMPAIGN_UPDATE_SUCCESS
          redirect_to @campaign
        end
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign ||= Campaign.find(params[:id])
    respond_to do |format|
      if @campaign.cancel
        format.html do
          flash[:notice] = Stripstarter::Response::CAMPAIGN_DESTROY_SUCCESS
          redirect_to campaigns_path
        end
        format.json { render nothing: true, status: 200 }
      else
        format.html do
          flash[:notice] = Stripstarter::Response::CAMPAIGN_DESTROY_FAILURE
          redirect_to campaigns_path
        end
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    render json: Campaign.search(params["term"]), root: false
  end

  def finish
    @campaign ||= Campaign.find(params[:id])
  end

  def submit
    @campaign ||= Campaign.find(params[:id])
    respond_to do |format|
      if @campaign.try(:submit_for_review)
        format.json { render nothing: true, status: 200 }
        format.html do
          flash[:notice] = Stripstarter::Response::CAMPAIGN_SUBMIT_SUCCESS
          redirect_to campaigns_path
        end
      else
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
        format.html do
          flash[:notice] = Stripstarter::Response::CAMPAIGN_SUBMIT_FAILURE
          redirect_to root_path
        end
      end
    end
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name)
  end

  def ensure_owner
    @campaign = Campaign.find(params[:id])
    unless current_admin? || @campaign.owner == current_user
      flash[:notice] = Stripstarter::Response::UNAUTHORIZED_ACTION
      redirect_to campaigns_path
    end
    true
  end

  def ensure_performer
    @campaign = Campaign.find(params[:id])
    unless current_admin? || @campaign.performers.include?(current_user)
      flash[:notice] = Stripstarter::Response::UNAUTHORIZED_ACTION
      redirect_to campaigns_path
    end
    true
  end

  def ensure_owner_or_performer
    @campaign = Campaign.find(params[:id])
    unless current_admin? ||
           @campaign.owner == current_user ||
           @campaign.performers.include?(current_user)
      flash[:notice] = Stripstarter::Response::UNAUTHORIZED_ACTION
      redirect_to campaigns_path
    end
    true
  end
end

app/views/campaigns/_form.html.erb
<%= form_for @campaign, html: {class: "form-horizontal col-md-6", role: "form"} do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-md-12">
      <input name="campaign[name]" type="text" class="form-control" placeholder="Campaign name...">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-6 actions">
      <input type="submit" value="Create" class="btn btn-success">
    </div>
  </div>
<% end %>

app/views/campaigns/_newest.html.erb
<div class="row">
  <div class="col-md-8">
    <h3 class="text-center">Newest Campaigns</h3>

    <br />
    <br />

    <table class="table table-striped">
      <% @newest_campaigns.each do |campaign| %>
        <tr>
          <td><%= link_to "#{campaign.name}", campaign_path(campaign) %></td>
          <td><%= campaign.created_at.strftime("%B %d, %Y") %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/campaigns/_top.html.erb
<div class="row">
  <div class="col-md-8">
    <h3 class="text-center">Top Campaigns</h3>

    <br />
    <br />

    <table class="table table-striped">
      <% @top_campaigns.each do |campaign| %>
        <tr>
          <td><%= link_to "#{campaign.name}", campaign_path(campaign) %></td>
          <td><%= "$#{campaign.amount}" %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/finish.html.erb
<!-- <p>THIS PAGE WILL LIST THE FEATURES AND AMOUNT FOR A PARTICULAR CAMPAIGN REFERENCED BY @campaign</p>

<p>IT IS ONLY ACCESSIBLE IF THE CURRENT USER IS A PERFORMER (OR ADMIN) WHO OWNS THE CAMPAIGN SPECIFIED.</p>

<p>THE FEATURES WILL ALL HAVE A LENGTHY DESCRIPTION OF WHAT EXACTLY IS REQUESTED (THE SAME DESCRIPTION THE PERSON MAKING THE CAMPAIGN WOULD SEE)</p>

<p>THERE WILL BE AN UPLOAD FORM WHICH POSTS TO PerformancePhotos#create WHICH SAVES THE ATTACHMENT VIA PAPERCLIP TO A PRIVATE FOLDER IN THE BUCKET.  THIS FORM IS INLINE AND THE POST REQUEST IS ASYNCHRONOUS.</p>

<p>ONCE THE PERFORMER HAS UPLOADED ENOUGH PHOTOS THEY FEEL IS SUFFICIENT, THEY CLICK 'Continue' WHICH MAKES A POST REQUEST TO Campaigns#submit_for_review.</p>

<p>FROM THERE, THE CAMPAIGN WILL BE MARKED AS "in_review" AND THERE WILL BE AN ADMIN INTERFACE TO REVIEW CAMPAIGNS AND MARK THEM AS "completed" OR BACK TO "active"</p> -->

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<h3>Submitting photos for <%= @campaign.name.truncate(20) %></h3>
<div class="row">
  <div class="col-md-6">
    <table class="table">
      <tr>
        <th class="col-md-8"></th>
        <th class="col-md-4"></th>
      </tr>
      <% @campaign.photos.each do |photo| %>
        <tr>
          <td><%= image_tag photo_path(photo, style: "thumb") %></td>
          <td>
            <%= link_to photo_destroy_path(photo_id: photo.id), method: "delete" do %>
              <button class="btn btn-danger">X</button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <%= form_for (Photo.new), url: photos_path, html: {class: "form-horizontal form-inline col-md-6", role: "form"} do |f| %>
    <%= hidden_field_tag 'campaign_id', @campaign.id %>
    <div class="form-group">
      <div class="col-md-12">
        <%= f.label :image %>
        <%= f.file_field :image, name: "photo[image]" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-12 actions">
        <input type="submit" value="Add Photo" class="btn btn-success">
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-md-1">
    <%= link_to campaign_submit_path(@campaign), method: "post" do %>
      <button class="btn btn-success">Submit for review!</button>
    <% end %>
  </div>
</div>

app/views/campaigns/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="row">
  <div class="col-md-8">
    <div class="col-sm-2">
      <button class="btn btn-default">
        <%= link_to 'New Campaign', new_campaign_path %>
      </button>
    </div>

    <form role="form" class="form-horizontal">
      <div class="form-group">
        <label for="campaign_search" class="col-sm-2 control-label">Search</label>
        <div class="col-sm-6">
          <input type="text" class="campaign_search form-control" id="campaign_search" placeholder="Find a campaign...">
        </div>
      </div>
    </form>
  </div>
</div>

<script type="text/javascript">
  $(function() {

    $('#search_box').hide();

    $('#campaign_search').autocomplete({
      minLength: 2,
      source: '<%= campaign_search_path(:json) %>',

      focus: function(event, ui) {
        $('#campaign_search').val(ui.item.value);
        return false;
      },

      select: function(event, ui) {
        $('#campaign_search').val(ui.item.value);
        $('#link_origin_id').val(ui.item.id);
        return false;
      }
    })
    .data( "ui-autocomplete" )._renderItem = function( ul, item ) {
      return $( "<li></li>" )
        .data( "autocomplete-item", item )
        .append( "<a href=" + item.url + ">" + item.value +  "</a>" )
        .appendTo( ul );
    };
  });
</script>

<%= render 'top' if defined?(@top_campaigns) %>
<%= render 'newest' if defined?(@newest_campaigns) %>

app/views/campaigns/new.html.erb
<h3>Create a campaign</h3>

<%= render 'form' %>

app/views/campaigns/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if current_admin? %>
  <%= "STATUS: #{@campaign.status}" %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <td class="col-md-2"><strong>Starring: </strong></td>
        <td class="col-md-10">
          <% if !@campaign.performers.blank? %>
            <%= link_to performer_path(@campaign.performers.first), class: "col-md-2" do %>
              <div class="row">
                <%= image_tag @campaign.performers.first.avatar.url(:thumb), class: "img-circle" %>
              </div>
            <% end %>
          <% end %>
        </td>
      </tr> 
      <tr>
        <td class="col-md-2"><strong>Name: </strong></td>
        <td class="col-md-10"><%= @campaign.name %></td>
      </tr>
      <tr>
        <td class="col-md-2"><strong>Funding: </strong></td>
        <td class="col-md-10"><%= "$" + @campaign.amount.to_s %></td>
      </tr>
      <tr>
        <td class="col-md-2"><strong>Pledgers: </strong></td>
        <td class="col-md-10">
          <% @campaign.pledgers.limit(5).each do |pledger| %>
            <div class="col-md-2">
              <%= image_tag pledger.avatar.url(:thumb), class: "img-circle" %>
            </div>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="col-md-6">
      <% if !current_user.try(:is_a?, Performer) %>
        <%= form_tag pledges_path, method: "post" do |f| %>
          <%= hidden_field_tag 'pledge[campaign_id]', @campaign.id %>
          <%= hidden_field_tag 'pledge[amount]', "50" %>
          <%= submit_tag "Pledge $50!", :class => "btn btn-success" %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-6">
      <% if @campaign.performers.include?(current_user) || current_admin? %>
        <%= link_to campaign_finish_path(@campaign) do %>
          <button class="btn btn-success"><%= "Collect $#{@campaign.amount}!" %></button>
        <% end %>
      <% end %>
    </div>
  </div>
</div>